import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "@/app/(frontend)/globals.css"
import {NuqsAdapter} from "nuqs/adapters/next/app";
import {Providers} from "@/app/(frontend)/providers";
import {Toaster} from "sonner";
import Navbar from "@/components/layout/navbar";


const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
    display: "swap",
    fallback: ["system-ui", "sans-serif"],
});


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${inter.variable} ${inter.className} antialiased`}
        >
        <Providers>
            <NuqsAdapter>
                <Navbar/>
                {children}
                <Toaster position={"bottom-right"}/>
            </NuqsAdapter>
        </Providers>

        </body>
        </html>
    );
}
