import type { Metadata } from "next";
import {Inter } from "next/font/google";
import "./globals.css";
import {NuqsAdapter} from "nuqs/adapters/next/app";


const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
    display: "swap",
    fallback : ["system-ui", "sans-serif"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${inter.className} antialiased`}
      >
      <NuqsAdapter>
          {children}
      </NuqsAdapter>
      </body>
    </html>
  );
}
